import {
  GET_ALL_CONTENTS_OFFSET_BY_10,
  GET_ALL_CONTENTS_COUNT,
} from './allContents';
import { GET_IG_PHOTOS_OFFSET_BY_10, GET_IG_PHOTOS_COUNT } from './igPhotos';
import {
  GET_IG_STORY_CLIPS_OFFSET_BY_10,
  GET_IG_STORY_CLIPS_COUNT,
} from './igStoryClips';
import {
  GET_IG_STORY_SNAPS_OFFSET_BY_10,
  GET_IG_STORY_SNAPS_COUNT,
} from './igStorySnaps';
import { GET_IG_VIDEOS, GET_IG_VIDEOS_COUNT } from './igVideos';

export {
  GET_ALL_CONTENTS_OFFSET_BY_10,
  GET_ALL_CONTENTS_COUNT,
  GET_IG_PHOTOS_OFFSET_BY_10,
  GET_IG_PHOTOS_COUNT,
  GET_IG_STORY_CLIPS_OFFSET_BY_10,
  GET_IG_STORY_CLIPS_COUNT,
  GET_IG_STORY_SNAPS_OFFSET_BY_10,
  GET_IG_STORY_SNAPS_COUNT,
  GET_IG_VIDEOS,
  GET_IG_VIDEOS_COUNT,
};
